# Generated by Django 6.0.7 on 2026-08-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nepalikala', '0002_footercontent_herobanner_cart_cartitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wood Craft', 'Wood Craft'), ('Metal Art', 'Metal Art'), ('Textile', 'Textile'), ('Thangka', 'Thangka'), ('Pottery', 'Pottery'), ('Handmade Paper', 'Handmade Paper'), ('Basketry', 'Basketry')], default='Wood Craft', max_length=20),
        ),
    ]
